
#--------DATASET OPTIONS--------
#data range selection
condition_name_column: 1
condition_name_row: 5:10, 17:19, 26:28, 
metabolite_start_column: 5
metabolite_list_column_enabled: false
#if --metabolite_list_column_enabled: true-- then specify columns in --metabolite_list_column--
metabolite_list_column: 8,10:14,20
#type in a name of prime condition in --prime_condition_name-- to calculate time fold change 
prime_condition_name: Ga_500

#--------FILTER OPTIONS--------
#set minimum fold change
fold_change: 1.6
#set maximum p value
p_value: 0.05

#--------DATA LOADING OPTIONS--------
#TIP: better to use an excel workbook with only 1 sheet, otherwise specify one. 
data_path: D://Data Cells.xlsx
#specify sheet name if you have more than 1 sheet in excel workbook
excel_sheet: Sheet3
#if excel workbook contains more than 1 sheet --excel_sheet-- value will be used
open_popup_window: false




#--------EXPORT OPTIONS--------
#export plots for parametric and non-parametric data
#export data based on Kruskal Wallis
#NOTE! Kruskal Wallis p-value cannot be calculated for 2 conditions
export_median_plot: true
export_median_grid_plot: false
export_median_volcano_plot: true
export_median_xls_list: true
#export data based on ANOVA
export_mean_plot: true
export_mean_grid_plot: false
export_mean_volcano_plot: true
export_mean_xls_list: true
export_mean_stacked_bar_plot: true



#--------GRAPHICAL PLOTS OPTIONS--------
#show cutoff lines for log2(FC) and log10(p value). To disable lines set --0-- value
volcano_plot_log2_cutoff: 1.6
volcano_plot_log10_cutoff: 0.05
#set volcano plot title
volcano_plot_title:

plot_width: 800
plot_height: 900
num_cols_grid: 8
num_grid: 10
plot_title_size: 7
plot_geom_elements_size: 1.8
plot_x_axis_lable_angle: 0
plot_x_axis_lable_horizontal_adjust: 0.5
plot_axis_lable_size: 5
plot_axis_title_size: 7

