#data range selection

#
condition_name_column: 4
condition_name_row: 1,2:6,25:36
metabolite_start_column: 8
metabolite_list_column_enabled: false
#if --metabolite_list_column_enabled: true-- then specify columns in --metabolite_list_column--
metabolite_list_column: 8,10:14,20
#type in a name of prime condition in --prime_condition_name-- to calculate time fold change 
prime_condition_name: Ga 500

#filter options
fold_change: 1.6
p_value: 0.05

#data loading
#TIP: better to use an excel workbook with only 1 sheet, otherwise specify one. 
data_path: D://demo_metabolite_data.xlsx
#specify sheet name if you have more than 1 sheet in excel workbook
excel_sheet: Sheet1
#if excel workbook contains more than 1 sheet --excel_sheet-- value will be used
open_popup_window: true

#settings


#export plots for parametric and non-parametric data


#export data based on Kruskal Wallis
export_median_plot: true
export_median_grid_plot: true
export_median_volcano_plot: true
export_median_xls_list: true
#export data based on ANOVA
export_mean_plot: true
export_mean_grid_plot: true
export_mean_volcano_plot: true
export_mean_xls_list: true


plot_width: 800
plot_height: 900
num_cols_grid: 8
num_grid: 10
plot_title_size: 7
plot_x_axis_lable_angle: 0
plot_x_axis_lable_horizontal_adjust: 1
plot_axis_lable_size: 5
plot_axis_title_size: 7

